import type { Product } from "../gameCore.ts";

export const orderCatalog: Product[] = [
  {
    id: "cleaned-lab", name: "實驗級潔淨晶圓", customer: "材料分析實驗室", description: "單站清洗・長期供應",
    minYield: 95, baseYield: 97.5, materialCost: 120, diesPerLot: 25, unitPrice: 24, color: "#5ee8c5",
    recipe: ["clean"], objects: ["silicon-wafer", "clean-wafer"], requirements: { clean: 1 }, contractType: "permanent", requiredLots: 2, marketTier: 1,
  },
  {
    id: "cleaned-basic", name: "基礎清洗晶圓", customer: "在地元件廠", description: "低規格・長期供應",
    minYield: 88, baseYield: 94, materialCost: 85, diesPerLot: 25, unitPrice: 16, color: "#8bc7b4",
    recipe: ["clean"], objects: ["silicon-wafer", "clean-wafer"], requirements: { clean: 1 }, contractType: "permanent", requiredLots: 3, marketTier: 1,
  },
  {
    id: "cleaned-process", name: "製程用潔淨晶圓", customer: "封測代工廠", description: "中量供應・長期訂單",
    minYield: 91, baseYield: 95.2, materialCost: 100, diesPerLot: 25, unitPrice: 19, color: "#70cbb5",
    recipe: ["clean"], objects: ["silicon-wafer", "clean-wafer"], requirements: { clean: 1 }, contractType: "permanent", requiredLots: 4, marketTier: 1,
  },
  {
    id: "cleaned-optics", name: "光學級潔淨晶圓", customer: "精密光學中心", description: "高潔淨度・短期委託",
    minYield: 97, baseYield: 98.1, materialCost: 140, diesPerLot: 25, unitPrice: 30, color: "#8ff0dd",
    recipe: ["clean"], objects: ["silicon-wafer", "clean-wafer"], requirements: { clean: 1 }, contractType: "limited", requiredLots: 2, contractRuns: 3, marketTier: 1,
  },
  {
    id: "cleaned-sensor", name: "感測器潔淨晶圓", customer: "微感測研究所", description: "研究用料・小量訂單",
    minYield: 96, baseYield: 97.8, materialCost: 150, diesPerLot: 25, unitPrice: 28, color: "#66d8c0",
    recipe: ["clean"], objects: ["silicon-wafer", "clean-wafer"], requirements: { clean: 1 }, contractType: "limited", requiredLots: 3, contractRuns: 3, marketTier: 1,
  },
  {
    id: "cleaned-medical", name: "醫材實驗晶圓", customer: "生醫研發中心", description: "少量高酬勞・短期訂單",
    minYield: 96, baseYield: 97.4, materialCost: 155, diesPerLot: 25, unitPrice: 34, color: "#9aecd8",
    recipe: ["clean"], objects: ["silicon-wafer", "clean-wafer"], requirements: { clean: 1 }, contractType: "limited", requiredLots: 2, contractRuns: 2, marketTier: 1,
  },
  {
    id: "diode-mains", name: "整流二極體", customer: "民生電機", description: "成熟製程・長期供應",
    minYield: 78, baseYield: 91, materialCost: 550, diesPerLot: 800, unitPrice: 6.5, color: "#ffb648",
    recipe: ["clean", "furnace", "aligner", "etch", "package", "test"],
    objects: ["silicon-wafer", "clean-wafer", "doped-wafer", "patterned-wafer", "etched-wafer", "packaged-diode", "tested-diode"],
    requirements: { clean: 1, furnace: 1, aligner: 1, etch: 1, package: 1, test: 1 }, contractType: "permanent", requiredLots: 6, marketTier: 2,
  },
  {
    id: "diode-solar", name: "太陽能旁路二極體", customer: "日照能源", description: "耐熱規格・專案訂單",
    minYield: 84, baseYield: 92, materialCost: 650, diesPerLot: 800, unitPrice: 8.2, color: "#ffd166",
    recipe: ["clean", "furnace", "aligner", "etch", "package", "test"],
    objects: ["silicon-wafer", "clean-wafer", "doped-wafer", "patterned-wafer", "etched-wafer", "packaged-diode", "tested-diode"],
    requirements: { clean: 1, furnace: 1, aligner: 1, etch: 1, package: 1, test: 1 }, contractType: "limited", requiredLots: 4, contractRuns: 3, marketTier: 2,
  },
  {
    id: "diode-motor", name: "馬達保護二極體", customer: "動力控制公司", description: "工業規格・階段交貨",
    minYield: 82, baseYield: 91.5, materialCost: 600, diesPerLot: 800, unitPrice: 7.4, color: "#f5a65b",
    recipe: ["clean", "furnace", "aligner", "etch", "package", "test"],
    objects: ["silicon-wafer", "clean-wafer", "doped-wafer", "patterned-wafer", "etched-wafer", "packaged-diode", "tested-diode"],
    requirements: { clean: 1, furnace: 1, aligner: 1, etch: 1, package: 1, test: 1 }, contractType: "limited", requiredLots: 5, contractRuns: 4, marketTier: 2,
  },
  {
    id: "logic-dual-layer", name: "雙層邏輯控制晶片", customer: "智慧家電控制", description: "雙重微影・長期供應",
    minYield: 86, baseYield: 92, materialCost: 1050, diesPerLot: 850, unitPrice: 14.5, color: "#6dc3ff",
    recipe: ["clean", "furnace", "aligner", "etch", "clean", "furnace", "aligner", "etch", "package", "test"],
    objects: ["silicon-wafer", "clean-wafer", "doped-wafer", "patterned-wafer", "etched-wafer", "clean-wafer", "doped-wafer", "patterned-wafer", "etched-wafer", "packaged-logic", "tested-logic"],
    requirements: { clean: 1, furnace: 1, aligner: 1, etch: 1, package: 1, test: 1 }, contractType: "permanent", requiredLots: 4, marketTier: 2,
  },
  {
    id: "logic-meter", name: "電表邏輯晶片", customer: "智慧電網系統", description: "雙重微影・專案訂單",
    minYield: 89, baseYield: 93, materialCost: 1150, diesPerLot: 850, unitPrice: 16.5, color: "#88cfff",
    recipe: ["clean", "furnace", "aligner", "etch", "clean", "furnace", "aligner", "etch", "package", "test"],
    objects: ["silicon-wafer", "clean-wafer", "doped-wafer", "patterned-wafer", "etched-wafer", "clean-wafer", "doped-wafer", "patterned-wafer", "etched-wafer", "packaged-logic", "tested-logic"],
    requirements: { clean: 2, furnace: 2, aligner: 2, etch: 2, package: 1, test: 1 }, contractType: "limited", requiredLots: 3, contractRuns: 3, marketTier: 2,
  },
  {
    id: "analog-industrial", name: "類比控制晶片", customer: "工控自動化", description: "六吋晶圓・長期供應",
    minYield: 84, baseYield: 89, materialCost: 1400, diesPerLot: 900, unitPrice: 14.5, color: "#00d4a3",
    recipe: ["aligner", "deposition", "implant", "etch", "package", "test"],
    objects: ["silicon-wafer", "patterned-wafer", "deposited-wafer", "implanted-wafer", "etched-wafer", "packaged-analog", "tested-analog"],
    requirements: { aligner: 1, deposition: 1, implant: 1, etch: 1, package: 1, test: 1 }, contractType: "permanent", requiredLots: 4, marketTier: 3,
  },
  {
    id: "analog-audio", name: "音訊放大晶片", customer: "聲學電子", description: "低雜訊規格・限定專案",
    minYield: 87, baseYield: 90.5, materialCost: 1600, diesPerLot: 900, unitPrice: 17, color: "#42dfb2",
    recipe: ["aligner", "deposition", "implant", "etch", "package", "test"],
    objects: ["silicon-wafer", "patterned-wafer", "deposited-wafer", "implanted-wafer", "etched-wafer", "packaged-analog", "tested-analog"],
    requirements: { aligner: 1, deposition: 1, implant: 1, etch: 1, package: 1, test: 1 }, contractType: "limited", requiredLots: 3, contractRuns: 3, marketTier: 3,
  },
  {
    id: "analog-sensor", name: "感測前端晶片", customer: "智慧儀器", description: "高精度規格・試產委託",
    minYield: 89, baseYield: 91.5, materialCost: 1800, diesPerLot: 900, unitPrice: 19, color: "#2acfa5",
    recipe: ["aligner", "deposition", "implant", "etch", "package", "test"],
    objects: ["silicon-wafer", "patterned-wafer", "deposited-wafer", "implanted-wafer", "etched-wafer", "packaged-analog", "tested-analog"],
    requirements: { aligner: 2, deposition: 2, implant: 2, etch: 2, package: 1, test: 2 }, contractType: "limited", requiredLots: 2, contractRuns: 3, marketTier: 3,
  },
  {
    id: "analog-dual-layer", name: "雙層電源管理晶片", customer: "儲能控制科技", description: "重複薄膜製程・長期供應",
    minYield: 88, baseYield: 92, materialCost: 2700, diesPerLot: 900, unitPrice: 30, color: "#3fe0ca",
    recipe: ["clean", "aligner", "deposition", "implant", "etch", "clean", "aligner", "deposition", "implant", "etch", "package", "test"],
    objects: ["silicon-wafer", "clean-wafer", "patterned-wafer", "deposited-wafer", "implanted-wafer", "etched-wafer", "clean-wafer", "patterned-wafer", "deposited-wafer", "implanted-wafer", "etched-wafer", "packaged-analog", "tested-analog"],
    requirements: { clean: 2, aligner: 2, deposition: 2, implant: 2, etch: 2, package: 2, test: 2 }, contractType: "permanent", requiredLots: 3, marketTier: 3,
  },
  {
    id: "mcu-edge", name: "低功耗微控制器", customer: "邊緣系統", description: "多層製程・長期供應",
    minYield: 90, baseYield: 92, materialCost: 4200, diesPerLot: 1000, unitPrice: 31, color: "#8c7bff",
    recipe: ["stepper", "deposition", "implant", "etch", "package", "test"],
    objects: ["silicon-wafer", "precision-patterned-wafer", "deposited-wafer", "implanted-wafer", "etched-wafer", "packaged-mcu", "tested-mcu"],
    requirements: { stepper: 1, deposition: 2, implant: 2, etch: 2, package: 2, test: 2 }, contractType: "permanent", requiredLots: 3, marketTier: 4,
  },
  {
    id: "mcu-wearable", name: "穿戴裝置控制器", customer: "健康穿戴科技", description: "超低功耗・限定量產",
    minYield: 91, baseYield: 93, materialCost: 4500, diesPerLot: 1000, unitPrice: 35, color: "#a594ff",
    recipe: ["stepper", "deposition", "implant", "etch", "package", "test"],
    objects: ["silicon-wafer", "precision-patterned-wafer", "deposited-wafer", "implanted-wafer", "etched-wafer", "packaged-mcu", "tested-mcu"],
    requirements: { stepper: 2, deposition: 2, implant: 2, etch: 2, package: 2, test: 2 }, contractType: "limited", requiredLots: 2, contractRuns: 3, marketTier: 4,
  },
  {
    id: "mcu-auto", name: "車用安全控制器", customer: "智慧車電", description: "高可靠度・驗證批次",
    minYield: 94, baseYield: 95, materialCost: 5200, diesPerLot: 1000, unitPrice: 42, color: "#b8a8ff",
    recipe: ["stepper", "deposition", "implant", "etch", "package", "test"],
    objects: ["silicon-wafer", "precision-patterned-wafer", "deposited-wafer", "implanted-wafer", "etched-wafer", "packaged-mcu", "tested-mcu"],
    requirements: { stepper: 3, deposition: 3, implant: 3, etch: 3, package: 3, test: 3 }, contractType: "limited", requiredLots: 2, contractRuns: 2, marketTier: 4,
  },
  {
    id: "mcu-triple-layer", name: "三層工控微控制器", customer: "工業邊緣運算", description: "三重微影・長期供應",
    minYield: 92, baseYield: 94.5, materialCost: 7800, diesPerLot: 1000, unitPrice: 62, color: "#d0b3ff",
    recipe: ["stepper", "deposition", "implant", "etch", "clean", "stepper", "deposition", "implant", "etch", "clean", "stepper", "deposition", "implant", "etch", "package", "test"],
    objects: ["silicon-wafer", "precision-patterned-wafer", "deposited-wafer", "implanted-wafer", "etched-wafer", "clean-wafer", "precision-patterned-wafer", "deposited-wafer", "implanted-wafer", "etched-wafer", "clean-wafer", "precision-patterned-wafer", "deposited-wafer", "implanted-wafer", "etched-wafer", "packaged-mcu", "tested-mcu"],
    requirements: { clean: 3, stepper: 3, deposition: 3, implant: 3, etch: 3, package: 3, test: 3 }, contractType: "permanent", requiredLots: 2, marketTier: 4,
  },
];
